
PACKAGE         = 'bzflag'
PACKAGE_NAME    = 'BZFlag'
PACKAGE_TARNAME = 'bzflag'

MAJOR_VERSION = 2
MINOR_VERSION = 99
REVISION      = 60

PROTOCOL = '0118'


BZROBOTS_PROTO_VERSION = '0001'


BUILD_TYPE = 'DEVEL'  -- ('DEVEL' or 'STABLE' or 'MAINT')


COPYRIGHT = 'Copyright (c) 1993-2011 Tim Riker'

PACKAGE_URL = 'http://BZFlag.org'

PACKAGE_BUGREPORT = 'http://BZFlag.org'

