AM_CPPFLAGS = -I$(top_srcdir)/include $(LIBCURL_CPPFLAGS) \
	-DINSTALL_DATA_DIR=\"$(pkgdatadir)\" $(X_CFLAGS)
if GNU_GCC
  AM_CFLAGS = -fsigned-char
  AM_CXXFLAGS = -fsigned-char
else
  AM_CFLAGS =
  AM_CXXFLAGS =
endif
