

if (not _ACTION) then
  return
end

local sourceFile = nil

if (_ACTION:match('^vs')) then
  sourceFile = 'config_msvc.h'
elseif ((_ACTION == 'gmake') or
        (_ACTION == 'xcode3') or
        (_ACTION == 'codelite') or
        (_ACTION == 'codeblocks')) then
  sourceFile = 'config_ref.h'
end

if (not sourceFile) then
  return
end


print(('-'):rep(80))
print('Creating src/include/config.h')

local f = assert(io.open('../src/include/config.h', 'wt'))

local ref = assert(io.open(sourceFile))
local text = ref:read('*a')
ref:close()

f:write('\n')
f:write('/* Generated by premake4_config/config_h.lua */\n')
f:write('\n')
f:write(text)
f:write('\n')

f:close()

print(('-'):rep(80))
