#!/bin/sh

if [ ! -r config ] ; then
 echo $0 be run in the project home directory
fi
eval `grep VERSIONID config | sed -e 's/ //g'`
if [ -z "$1" ] ; then
 version=$VERSIONID.`date +%Y%m%d`
else
 version=$VERSIONID
fi
date=`date --rfc-822`
sed -e "s/@VERSION@/$version/g" -e "s/@DATE@/$date/g" < debian/changelog.in > debian/changelog

# cvs/non-cvs builds should conflict and replace each other.
dpkg-buildpackage -us -uc -rfakeroot
