/* bzflag
 * Copyright (c) 1993 - 2003 Tim Riker
 *
 * This package is free software;  you can redistribute it and/or
 * modify it under the terms of the license found in the file
 * named COPYING that should have accompanied this file.
 *
 * THIS PACKAGE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

/* win32/config.h.  Generated by hand by Jeff Myers 6-12-03 */
/* this config is just for visual C++ since it donsn't use automake*/

/* This is a really really fugly hack to get around winsock sillyness
 * The newer versions of winsock have a socken_t typedef, and there
 * doesn't seem to be any way to tell the versions apart. However,
 * VC++ helps us out here by treating typedef as #define
 * If we've got a socklen_t typedefed, define HAVE_SOCKLEN_T to
 * avoid #define'ing it in common.h */
#if defined socklen_t
#define HAVE_SOCKELEN_T
#endif

#include <stdio.h>
#include <string.h>
// to get the version in the right format YYYYMMDD
inline int getBuildDate()
{
	int year = 1900,month = 0,day = 0;
	char temp[512];
	char monthStr[512];
	strcpy(temp,__DATE__);
	sscanf(temp,"%s %d %d",monthStr,&day,&year);

	if (strcmp(monthStr,"Jan")==0)
		month = 1;
	else if (strcmp(monthStr,"Feb")==0)
		month = 2;
	else if (strcmp(monthStr,"Mar")==0)
		month = 3;
	else if (strcmp(monthStr,"Apr")==0)
		month = 4;
	else if (strcmp(monthStr,"May")==0)
		month = 5;
	else if (strcmp(monthStr,"Jun")==0)
		month = 6;
	else if (strcmp(monthStr,"Jul")==0)
		month = 7;
	else if (strcmp(monthStr,"Aug")==0)
		month = 8;
	else if (strcmp(monthStr,"Sep")==0)
		month = 9;
	else if (strcmp(monthStr,"Oct")==0)
		month = 10;
	else if (strcmp(monthStr,"Nov")==0)
		month = 11;
	else if (strcmp(monthStr,"Dec")==0)
		month = 12;

	return (year*10000) + (month*100)+ day;
}

// protocoll version
#ifndef BZ_PROTO_VERSION
#define BZ_PROTO_VERSION "109a"
#endif //BZ_PROTO_VERSION

#ifndef BZ_MAJOR_VERSION
#define BZ_MAJOR_VERSION	1
#endif

#ifndef BZ_MINOR_VERSION
#define BZ_MINOR_VERSION	9
#endif

#ifndef BZ_REV
#define BZ_REV				0
#endif

#ifndef BZ_BUILD_OS
#ifdef _DEBUG
#define BZ_BUILD_OS			"W32VCD"
#else
#define BZ_BUILD_OS			"W32VC"
#endif
#endif

#ifndef BZ_BUILD_SOURCE
#define BZ_BUILD_SOURCE		 "CVS"
#endif

#ifndef BZ_BUILD_DATE
#define BZ_BUILD_DATE		getBuildDate()
#endif

/* Time Bomb expiration */
/* #undef TIME_BOMB */

/* Debug Rendering */
/* #undef DEBUG_RENDERING */

/* Enabling Robots */
#define ROBOT 1

/* Enabling Snapping */
#define SNAPPING 1

/* On windows, strcasecmp is really stricmp */
#define HAVE_STRICMP 1
