// statTemplates.cpp : Defines the entry point for the DLL application.
//

#include "statTemplates.h"
#include "bzfsAPI.h"
#include "plugin_utils.h"

double start;
std::string getFileHeader ( void )
{
  start = bz_getCurrentTime();
  std::string page ="<HTML><HEAD></HEAD><BODY>\n<BR>\n";

  std::string publicAddr = bz_getPublicAddr().c_str();
  page = "Stats for";
  page += publicAddr + "<br>\n";

  return page;
}

std::string getFileFooter ( void )
{
  return format("<br><hr>Page generated by webstats in %f seconds\n",bz_getCurrentTime()-start);
}




// Local Variables: ***
// mode:C++ ***
// tab-width: 8 ***
// c-basic-offset: 2 ***
// indent-tabs-mode: t ***
// End: ***
// ex: shiftwidth=2 tabstop=8
