
bzlib_project 'libClientBase'

  includedirs { '.', '../bzflag' }

  files {
    'ActionBinding.cpp',              'ActionBinding.h',
    'BaseLocalPlayer.cpp',            'BaseLocalPlayer.h',
    'ClientFlag.h',
    'ClientIntangibilityManager.cpp', 'ClientIntangibilityManager.h',
    'CommandsStandard.cpp',           'CommandsStandard.h',
    'EntryZone.cpp',                  'EntryZone.h',
    'EventClient.cpp',
    'EventClientList.cpp',
    'EventHandler.cpp',
    'FlashClock.cpp',                 'FlashClock.h',
    'GfxBlock.cpp',
    'GuidedMissileStrategy.cpp',      'GuidedMissileStrategy.h',
    'LocalPlayer.cpp',                'LocalPlayer.h',
    'Player.cpp',                     'Player.h',
    'PointShotStrategy.cpp',          'PointShotStrategy.h',
    'Region.cpp',                     'Region.h',
    'RegionPriorityQueue.cpp',        'RegionPriorityQueue.h',
    'RemotePlayer.cpp',               'RemotePlayer.h',
    'RobotPlayer.cpp',                'RobotPlayer.h',
    'Roster.cpp',                     'Roster.h',
    'SegmentedShotStrategy.cpp',      'SegmentedShotStrategy.h',
    'ServerLink.cpp',                 'ServerLink.h',
    'ShockWaveStrategy.cpp',          'ShockWaveStrategy.h',
    'ShotPath.cpp',                   'ShotPath.h',
    'ShotPathSegment.cpp',            'ShotPathSegment.h',
    'ShotStatistics.cpp',             'ShotStatistics.h',
    'ShotStrategy.cpp',               'ShotStrategy.h',
    'TargetingUtils.cpp',             'TargetingUtils.h',
    'Weapon.cpp',                     'Weapon.h',
    'World.cpp',                      'World.h',
    'WorldBuilder.cpp',               'WorldBuilder.h',
    'WorldDownLoader.cpp',            'WorldDownLoader.h',
    'WorldPlayer.cpp',                'WorldPlayer.h',
    'callbacks.cpp',                  'callbacks.h',
    'clientCommands.cpp',
    'clientConfig.cpp',               'clientConfig.h',
    'clientvars.h',
    'defaultBZDB.cpp',                'defaultBZDB.h',
    'playing.cpp',                    'playing.h',
  }
  if (not _OPTIONS['disable-bzrobots']) then
    files {
      '../bzflag/AutoHunt.cpp',               '../bzflag/AutoHunt.h',
      '../bzflag/AutoPilot.cpp',              '../bzflag/AutoPilot.h',
      '../bzflag/BackgroundRenderer.cpp',     '../bzflag/BackgroundRenderer.h',
      '../bzflag/CommandsImplementation.cpp',
      '../bzflag/ComposeDefaultKey.cpp',      '../bzflag/ComposeDefaultKey.h',
      '../bzflag/ControlPanel.cpp',           '../bzflag/ControlPanel.h',
      '../bzflag/CrackedGlass.cpp',           '../bzflag/CrackedGlass.h',
      '../bzflag/Daylight.cpp',               '../bzflag/Daylight.h',
      '../bzflag/DebugDrawing.cpp',           '../bzflag/DebugDrawing.h',
      '../bzflag/Downloads.cpp',              '../bzflag/Downloads.h',
      '../bzflag/DynamicWorldText.cpp',       '../bzflag/DynamicWorldText.h',
      '../bzflag/EffectsRenderer.cpp',        '../bzflag/EffectsRenderer.h',
      '../bzflag/FontSizer.cpp',              '../bzflag/FontSizer.h',
      '../bzflag/ForceFeedback.cpp',          '../bzflag/ForceFeedback.h',
      '../bzflag/HUDDialog.cpp',              '../bzflag/HUDDialog.h',
      '../bzflag/HUDDialogStack.cpp',         '../bzflag/HUDDialogStack.h',
      '../bzflag/HUDNavigationQueue.cpp',     '../bzflag/HUDNavigationQueue.h',
      '../bzflag/HUDRenderer.cpp',            '../bzflag/HUDRenderer.h',
      '../bzflag/HUDui.cpp',                  '../bzflag/HUDui.h',
      '../bzflag/HUDuiControl.cpp',           '../bzflag/HUDuiControl.h',
      '../bzflag/HUDuiDefaultKey.cpp',        '../bzflag/HUDuiDefaultKey.h',
      '../bzflag/HUDuiElement.cpp',           '../bzflag/HUDuiElement.h',
      '../bzflag/HUDuiFrame.cpp',             '../bzflag/HUDuiFrame.h',
      '../bzflag/HUDuiImage.cpp',             '../bzflag/HUDuiImage.h',
      '../bzflag/HUDuiLabel.cpp',             '../bzflag/HUDuiLabel.h',
      '../bzflag/HUDuiList.cpp',              '../bzflag/HUDuiList.h',
      '../bzflag/HUDuiTypeIn.cpp',            '../bzflag/HUDuiTypeIn.h',
      '../bzflag/HubComposeKey.cpp',          '../bzflag/HubComposeKey.h',
      '../bzflag/LocalCommand.cpp',           '../bzflag/LocalCommand.h',
      '../bzflag/LocalFontFace.cpp',          '../bzflag/LocalFontFace.h',
      '../bzflag/MainWindow.cpp',             '../bzflag/MainWindow.h',
      '../bzflag/Mumble.cpp',                 '../bzflag/Mumble.h',
      '../bzflag/Plan.cpp',                   '../bzflag/Plan.h',
      '../bzflag/PlatformSound.cpp',          '../bzflag/PlatformSound.h',
      '../bzflag/PlayerAvatarManager.cpp',    '../bzflag/PlayerAvatarManager.h',
      '../bzflag/RadarRenderer.cpp',          '../bzflag/RadarRenderer.h',
      '../bzflag/Roaming.cpp',                '../bzflag/Roaming.h',
      '../bzflag/RoofTops.cpp',               '../bzflag/RoofTops.h',
      '../bzflag/SceneRenderer.cpp',
      '../bzflag/ScoreboardRenderer.cpp',     '../bzflag/ScoreboardRenderer.h',
      '../bzflag/ServerCommandKey.cpp',       '../bzflag/ServerCommandKey.h',
      '../bzflag/ShotStats.cpp',              '../bzflag/ShotStats.h',
      '../bzflag/ShotStatsDefaultKey.cpp',    '../bzflag/ShotStatsDefaultKey.h',
      '../bzflag/SilenceDefaultKey.cpp',      '../bzflag/SilenceDefaultKey.h',
      '../bzflag/StandardTankAvatar.cpp',     '../bzflag/StandardTankAvatar.h',
      '../bzflag/ThirdPersonVars.cpp',        '../bzflag/ThirdPersonVars.h',
      '../bzflag/TrackMarks.cpp',             '../bzflag/TrackMarks.h',
      '../bzflag/WeatherRenderer.cpp',        '../bzflag/WeatherRenderer.h',
      '../bzflag/commands.h',
      '../bzflag/sound.cpp',                  '../bzflag/sound.h',
      '../bzflag/stars.cpp',                  '../bzflag/stars.h',
    }
  end



